### ISSUE TITLE
'dbt_metrics_default_calendar' is hard-coded in metric.sql

### ISSUE THREAD

**Issue by ataft** [dbt-labs/dbt_metrics#29] opened 2022-04-20 22:26 UTC
A reference to 'dbt_metrics_default_calendar' is hard coded in [metric.sql](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/metric.sql#L3).
`-- depends on: {{ ref('dbt_metrics_default_calendar') }}`

It should be a dynamic reference to the calendar table, allowing for a [custom calendar](https://github.com/dbt-labs/dbt_metrics#calendar), similar to [get_metric_sql.sql](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/get_metric_sql.sql#L25).

**Comment by callum-mcdata** [comment] 2022-06-01 15:19
Hi Andrew 👋 

This might be tricky given the nature of [forced dependencies](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies). In case you're unfamiliar with it, I suspect the logic goes as following:
1. The `metric.sql` macro is called from the model 
2. The `metric.sql` macro is compiled
3. The `metric.sql` macro is run with all the parameters provided and produces SQL statement.
4. The SQL Statement produced is then returned to the base model and target file is created.
5. Then the actual run part of dbt kicks in. 

The issue is that DAG relationships are recognized in Step 2 and that the compilation occurs in a macro and not a model.

If the file in question were a model, it would have multiple rounds of compilation. It would first insert the correct string provided by the variable and then correctly recognize the `ref` function and store that DAG relationship. But because this is a macro and only has the **first** level of compilation, the forced dependency has to be hard-coded. 

I'm asking around internally if there are any workarounds for this particular issue but if there **aren't**, I think we have two paths forward.
1. Leave the forced dependency in
2. Take the forced dependency out

I lean towards option 2. While it is beneficial to know that the metric references a calendar model, I lean towards correctness for the information in the DAG. Having an incorrect DAG relationship for anyone using a custom calendar feels like the wrong solution, even if it is correct for those not using a custom calendar.

**Comment by callum-mcdata** [comment] 2022-06-01 21:56
Well @ataft you can ignore the above comment. I figured out how to handle it in #32 . This is a breaking change though - it requires the user to enter in the custom calendar information as just the model name, as opposed to the ref('model name') pattern that is consistent throughout the rest of dbt. 

Unfortunately I wasn't able to find any other workaround so I've got a draft PR up for review on whether we merge that or not. I'd follow that PR for more discussion on whether people believe it should get merged or not!

**Closed** 2022-06-07 16:29 UTC
Labels: bug
