### ISSUE TITLE
--defer and metrics

### ISSUE THREAD

**Issue by pquadri** [dbt-labs/dbt_metrics#67] opened 2022-07-29 08:37 UTC
Hello everyone, we are trying out dbt_metrics and saw a strange problem within our CI environment.
We use `dbt build --select state:modified+ --defer` to only execute models that have changed, and since metrics themselves do not count as a model but rather are CTE, they of course are not executed. 
What happens instead is when the CTE for the metric is compiled it does not respect the --defer flag and uses the current schema rather than the deferred one, does this make sense? 

probably related to https://github.com/dbt-labs/dbt-core/issues/5525

**Comment by callum-mcdata** [comment] 2022-07-29 20:39
Closing out as the issue is known in #64 and can follow along there as we begin to address it!

**Closed by callum-mcdata** 2022-07-29 20:39 UTC
