### ISSUE TITLE
Multiple metrics macro does not include results when dimension has NULL values

### ISSUE THREAD

**Issue by AntonioSBC** [dbt-labs/dbt_metrics#109] opened 2022-09-13 17:39 UTC
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

It looks like there is a issue when grouping metrics by dimensions with NULL values. I have a dimension that in certain case has NULL value, and when I use the macro for multiple metrics including this dimension the output does not include the rows where this dimension is NULL and the metric value is greater than zero.

### Expected Behavior

In the output of the model, I would expect to have a row that include metrics value also when the dimension is NULL.

### Steps To Reproduce

fix

### Environment

```markdown
- dbt-adapter & version:
- dbt_metrics version:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by callum-mcdata** [comment] 2022-09-13 18:50
@AntonioSBC can you provide the an example of the output and what you'd expect it to look like?

Additionally can you take a look at the compiled SQL and trace back the CTE where the issue is arising? I've taken a look at the codebase and I can't think of anywhere we might be filtering out null values 🤔

**Comment by AntonioSBC** [comment] 2022-09-14 14:27
> @AntonioSBC can you provide the an example of the output and what you'd expect it to look like?
> 
> Additionally can you take a look at the compiled SQL and trace back the CTE where the issue is arising? I've taken a look at the codebase and I can't think of anywhere we might be filtering out null values 🤔

Hi @callum-mcdata. I have taken a look into compiled SQL and it seems to filter out NULL when there is the CTE first_metric_final where there is the LEFT OUTER JOIN  between __spine_time and __aggregate tables.
The WHERE condition on __spine_time.date_day filters out the rows with dimension NULL  even if the metrics value is greater than zero. Maybe is also connected to LEFT OUTER JOIN. I tried to run the query with a FULL OUTER JOIN and the conditions applied for both date_day fields with OR clause. Here the compiled SQL:
`with calendar as ( 
select * 
from SANDBOX.DBT.dbt_metrics_default_calendar)
,sellers_properties__aggregate as ( 
select
date_day,
"country",
"primary_city",
count(distinct property_to_aggregate) as sellers_properties
from (
select
cast("creation_datetime" as date) as metric_date_day, -- timestamp field
SANDBOX.DBT.dbt_metrics_default_calendar.date_day as date_day,
-- ALL DIMENSIONS
"country",
"primary_city",
"property_display_id" as property_to_aggregate
from SANDBOX.DBT.seller_leads_to_acquisition
left join SANDBOX.DBT.dbt_metrics_default_calendar
on cast("creation_datetime" as date) = date_day
where 1=1
-- metric start/end dates also applied here to limit incoming data
-- metric filter clauses...
) as base_query
group by 
1
,
2,3
)
,sellers_properties__dims as (
select distinct
"country"
,
"primary_city"
from sellers_properties__aggregate
)
,sellers_properties__spine_time as (
select
calendar.date_day
,sellers_properties__dims."country"
,sellers_properties__dims."primary_city"
from calendar
cross join sellers_properties__dims
group by 
1
,
2,3
)
select
*
from sellers_properties__spine_time 
full outer join sellers_properties__aggregate
ON  
sellers_properties__spine_time.date_day = sellers_properties__aggregate.date_day AND
sellers_properties__spine_time."country" = sellers_properties__aggregate."country" AND
sellers_properties__spine_time."primary_city" = sellers_properties__aggregate."primary_city";
WHERE sellers_properties__spine_time.date_day='25-jun-2022' OR sellers_properties__aggregate.date_day='25-jun-2022'`

**Comment by callum-mcdata** [comment] 2022-09-23 02:30
Ah - I see what you all mean. This is because the using clause is not a NULL-Safe operator, which means that it doesn't match nulls. I'll be completely honest - I am against changing the default join behavior to a Null-Safe operator because of the number of edge cases that it could cause to fail silently. 

My suggested workaround would be to override NULL columns in the dimension in question in to some known quantity. It looks like `country` was provided as one of the dimensions included. I'd suggest altering the model this metric is built upon with the following logic:
> `ifnull(country, 'no country provided') as country`

That **should** resolve your issue and ensure that the join logic remains consistent regardless of the behavior of the underlying columns.

Does that solution work for you both?

**Comment by callum-mcdata** [comment] 2022-10-10 21:10
Closing this issue as it appears the workaround worked for y'all!

**Closed by callum-mcdata** 2022-10-10 21:10 UTC
Labels: bug

**Comment by clairetaylor352** [comment] 2022-10-19 14:16
Not sure about the etiquette of commenting on a closed issue, but I'm also coming across this.
It would be great if there were a way to make this work without altering my underlying model. Is there anyway we could have an `allow_nulls` configuration option or something?

**Comment by callum-mcdata** [comment] 2022-10-23 19:47
Hi @clairetaylor352 ! Given the above issues raised around null-safe and not null-safe operators, we are very hesitant to add configuration options that could cause silent failures. Is there a reason why altering the model for that specific dimension is not preferred?

**Comment by clairetaylor352** [comment] 2022-10-25 08:20
Because it's already a widely used model across our warehouse, and our convention is generally that NULL means not set so changing the column would break with that convention. 
Basically changing the field would not be an option. Adding a new field would, but would feel like a hack.
